name: check-commit

on:
  - push
  - pull_request

jobs:
  check-commit:
    runs-on: macOS-11

    steps:
      - name: Use Xcode 12.5.1
        run: |
          sudo xcode-select -s /Applications/Xcode_12.5.1.app/Contents/Developer

      - name: Current platform versions
        run: |
          sw_vers
          xcodebuild -version
          swift --version
          swiftlint version

      - name: Checkout default branch
        uses: actions/checkout@v2

      - name: Cache bundle
        uses: actions/cache@v2
        env:
          cache-name: bundle
        with:
          path: .bundle
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('Gemfile.lock') }}

      - name: Update bundle
        run: |
          make bundle

      - name: Run lint
        run: |
          make lint

      - name: Run test
        run: |
          make test

      - name: Run doc
        run: |
          make doc
